version: '3.8'

services:
  app:
    image: potteroff/nodejs2024q1-service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - my_network
    volumes:
      - ./src:/app/src
      - app-logs:/app/logs

  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: potteroff/postgres-16-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/postgresql/data
      - pg-logs:/var/log/postgresql
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  pg-data:
  pg-logs:
  app-logs:
