version: '3.8'

services:
  app:
    image: potteroff/nodejs2024q1-service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - my_network
    volumes:
      - ./src:/app/src

  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: potteroff/postgres-16-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres-data:
